import { StyleSheet } from "react-native";
import { theme, getColor, getSpacing, getTypography, getBorderRadius, getShadow } from "../../../src/styles/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: getColor('background.secondary'),
  },
  header: {
    backgroundColor: getColor('background.primary'),
    borderBottomWidth: 1,
    borderBottomColor: getColor('border.light'),
    paddingHorizontal: getSpacing('lg'),
    paddingTop: getSpacing('md'),
    paddingBottom: getSpacing('md'),
    ...getShadow('small'),
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: getSpacing('md'),
  },
  headerTitle: {
    ...getTypography('h2'),
    color: getColor('text.primary'),
  },
  markAllButton: {
    paddingHorizontal: getSpacing('md'),
    paddingVertical: getSpacing('sm'),
    borderRadius: getBorderRadius('full'),
    backgroundColor: getColor('accent.medicalBlue'),
    ...getShadow('small'),
  },
  markAllButtonText: {
    ...getTypography('bodySmall'),
    color: getColor('text.inverse'),
    fontWeight: '600',
  },
  categoriesContainer: {
    flexDirection: 'row',
  },
  categoryChip: {
    paddingHorizontal: getSpacing('md'),
    paddingVertical: getSpacing('sm'),
    borderRadius: getBorderRadius('full'),
    backgroundColor: getColor('background.secondary'),
    marginRight: getSpacing('sm'),
    borderWidth: 2,
    borderColor: getColor('border.light'),
    ...getShadow('small'),
  },
  categoryChipActive: {
    backgroundColor: getColor('accent.medicalBlue'),
    borderColor: getColor('accent.medicalBlue'),
    transform: [{ scale: 1.05 }],
    ...getShadow('medium'),
  },
  categoryChipText: {
    ...getTypography('bodySmall'),
    color: getColor('text.secondary'),
    fontWeight: '500',
  },
  categoryChipTextActive: {
    color: getColor('text.inverse'),
  },
  content: {
    flex: 1,
  },
  notificationsList: {
    paddingHorizontal: getSpacing('md'),
    paddingTop: getSpacing('md'),
  },
  dateSection: {
    marginBottom: getSpacing('lg'),
  },
  dateLabel: {
    ...getTypography('bodyMedium'),
    fontWeight: '700',
    color: getColor('text.primary'),
    marginBottom: getSpacing('md'),
    paddingHorizontal: getSpacing('sm'),
    paddingVertical: getSpacing('xs'),
    backgroundColor: getColor('background.primary'),
    borderRadius: getBorderRadius('sm'),
    alignSelf: 'flex-start',
    ...getShadow('small'),
  },
  notificationItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: getColor('background.primary'),
    borderRadius: getBorderRadius('lg'),
    padding: getSpacing('lg'),
    marginBottom: getSpacing('md'),
    ...getShadow('medium'),
    position: 'relative',
    borderWidth: 1,
    borderColor: getColor('border.light'),
  },
  notificationItemUnread: {
    backgroundColor: getColor('accent.medicalBlue') + '08',
    borderLeftWidth: 5,
    borderLeftColor: getColor('accent.medicalBlue'),
    borderColor: getColor('accent.medicalBlue') + '30',
    ...getShadow('large'),
  },
  notificationIcon: {
    width: 48,
    height: 48,
    borderRadius: getBorderRadius('full'),
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: getSpacing('md'),
    borderWidth: 2,
    borderColor: 'transparent',
  },
  notificationContent: {
    flex: 1,
  },
  notificationHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: getSpacing('xs'),
  },
  notificationTitle: {
    ...getTypography('bodyMedium'),
    fontWeight: '700',
    color: getColor('text.primary'),
    flex: 1,
    marginBottom: 2,
  },
  notificationTime: {
    ...getTypography('caption'),
    color: getColor('text.secondary'),
    marginLeft: getSpacing('sm'),
  },
  notificationMessage: {
    ...getTypography('body'),
    color: getColor('text.secondary'),
    lineHeight: 22,
    marginBottom: getSpacing('sm'),
    marginTop: getSpacing('xs'),
  },
  notificationFooter: {
    marginTop: getSpacing('xs'),
  },
  actionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: getSpacing('xs'),
    borderTopWidth: 1,
    borderTopColor: getColor('border.light'),
  },
  notificationAction: {
    ...getTypography('caption'),
    fontWeight: '600',
    marginLeft: getSpacing('xs'),
  },
  unreadIndicator: {
    position: 'absolute',
    top: getSpacing('lg'),
    right: getSpacing('lg'),
    width: 12,
    height: 12,
    borderRadius: getBorderRadius('full'),
    backgroundColor: getColor('accent.medicalBlue'),
    borderWidth: 2,
    borderColor: getColor('background.primary'),
  },
});
