/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as _notifications_clearReadNotifications from "../_notifications/clearReadNotifications.js";
import type * as _notifications_createNotification from "../_notifications/createNotification.js";
import type * as _notifications_getAdminNotifications from "../_notifications/getAdminNotifications.js";
import type * as _notifications_getNotificationById from "../_notifications/getNotificationById.js";
import type * as _notifications_getNotificationWithDetails from "../_notifications/getNotificationWithDetails.js";
import type * as _notifications_getPaymentRejectionNotifications from "../_notifications/getPaymentRejectionNotifications.js";
import type * as _notifications_getReferralHistoryNotifications from "../_notifications/getReferralHistoryNotifications.js";
import type * as _notifications_getRejectionHistoryNotifications from "../_notifications/getRejectionHistoryNotifications.js";
import type * as _notifications_getUnreadCount from "../_notifications/getUnreadCount.js";
import type * as _notifications_getUserNotifications from "../_notifications/getUserNotifications.js";
import type * as _notifications_markAllAsRead from "../_notifications/markAllAsRead.js";
import type * as _notifications_markAllNotificationsAsRead from "../_notifications/markAllNotificationsAsRead.js";
import type * as _notifications_markAsRead from "../_notifications/markAsRead.js";
import type * as _notifications_markNotificationAsRead from "../_notifications/markNotificationAsRead.js";
import type * as _notifications_markReferralHistoryAsRead from "../_notifications/markReferralHistoryAsRead.js";
import type * as _notifications_markRejectionHistoryAsRead from "../_notifications/markRejectionHistoryAsRead.js";
import type * as _notifications_sendAdminNotification from "../_notifications/sendAdminNotification.js";
import type * as _orientationSchedules_autoCreateSchedulesHandler from "../_orientationSchedules/autoCreateSchedulesHandler.js";
import type * as _orientationSchedules_bookOrientationSlot from "../_orientationSchedules/bookOrientationSlot.js";
import type * as _orientationSchedules_cancelOrientationBooking from "../_orientationSchedules/cancelOrientationBooking.js";
import type * as _orientationSchedules_debugListAll from "../_orientationSchedules/debugListAll.js";
import type * as _orientationSchedules_fixScheduleDates from "../_orientationSchedules/fixScheduleDates.js";
import type * as _orientationSchedules_getAvailableSchedules from "../_orientationSchedules/getAvailableSchedules.js";
import type * as _orientationSchedules_getSchedulesForDate from "../_orientationSchedules/getSchedulesForDate.js";
import type * as _orientationSchedules_getUserOrientationSession from "../_orientationSchedules/getUserOrientationSession.js";
import type * as _orientationSchedules_migrateTimeFields from "../_orientationSchedules/migrateTimeFields.js";
import type * as _orientationSchedules_migrateToPhilippineTime from "../_orientationSchedules/migrateToPhilippineTime.js";
import type * as _orientationSchedules_mutations from "../_orientationSchedules/mutations.js";
import type * as _orientationSchedules_queries from "../_orientationSchedules/queries.js";
import type * as _orientationSchedules_seedOrientationSchedules from "../_orientationSchedules/seedOrientationSchedules.js";
import type * as _orientationSchedules_timeUtils from "../_orientationSchedules/timeUtils.js";
import type * as admin_activityLogs from "../admin/activityLogs.js";
import type * as admin_adminMain from "../admin/adminMain.js";
import type * as admin_documents_referDocument from "../admin/documents/referDocument.js";
import type * as admin_documents_rejectDocument from "../admin/documents/rejectDocument.js";
import type * as admin_documents_sendReferralNotifications from "../admin/documents/sendReferralNotifications.js";
import type * as admin_documents_sendRejectionNotifications from "../admin/documents/sendRejectionNotifications.js";
import type * as admin_finalizeApplication from "../admin/finalizeApplication.js";
import type * as admin_fixFoodHandlerWorkflow from "../admin/fixFoodHandlerWorkflow.js";
import type * as admin_fixJobCategoryDocuments from "../admin/fixJobCategoryDocuments.js";
import type * as admin_inspectorAvailability from "../admin/inspectorAvailability.js";
import type * as admin_migrations_fixRejectionStatus from "../admin/migrations/fixRejectionStatus.js";
import type * as admin_orientation from "../admin/orientation.js";
import type * as admin_payments_rejectPayment from "../admin/payments/rejectPayment.js";
import type * as admin_payments_testResubmission from "../admin/payments/testResubmission.js";
import type * as admin_rejectApplicationFinal from "../admin/rejectApplicationFinal.js";
import type * as admin_rejectionHistory from "../admin/rejectionHistory.js";
import type * as admin_reviewDocument from "../admin/reviewDocument.js";
import type * as admin_seed from "../admin/seed.js";
import type * as admin_testFixRejectionStatus from "../admin/testFixRejectionStatus.js";
import type * as admin_updateAdminAccount from "../admin/updateAdminAccount.js";
import type * as admin_updateAdminAccountInternal from "../admin/updateAdminAccountInternal.js";
import type * as admin_validatePayment from "../admin/validatePayment.js";
import type * as applications_autoCancelExpiredApplications from "../applications/autoCancelExpiredApplications.js";
import type * as applications_checkRenewalEligibility from "../applications/checkRenewalEligibility.js";
import type * as applications_createApplication from "../applications/createApplication.js";
import type * as applications_createForm from "../applications/createForm.js";
import type * as applications_createRenewalApplication from "../applications/createRenewalApplication.js";
import type * as applications_deleteApplication from "../applications/deleteApplication.js";
import type * as applications_getApplicationById from "../applications/getApplicationById.js";
import type * as applications_getDocumentsWithClassification from "../applications/getDocumentsWithClassification.js";
import type * as applications_getFormById from "../applications/getFormById.js";
import type * as applications_getPreviousApplicationData from "../applications/getPreviousApplicationData.js";
import type * as applications_getUserApplications from "../applications/getUserApplications.js";
import type * as applications_getWithDocuments from "../applications/getWithDocuments.js";
import type * as applications_lib_renewalEligibility from "../applications/lib/renewalEligibility.js";
import type * as applications_list from "../applications/list.js";
import type * as applications_submitApplication from "../applications/submitApplication.js";
import type * as applications_updateApplication from "../applications/updateApplication.js";
import type * as applications_updateApplicationStatus from "../applications/updateApplicationStatus.js";
import type * as config_barangays from "../config/barangays.js";
import type * as config_paymentConstants from "../config/paymentConstants.js";
import type * as config_rejectionLimits from "../config/rejectionLimits.js";
import type * as crons from "../crons.js";
import type * as dashboard_getActivityLog from "../dashboard/getActivityLog.js";
import type * as dashboard_getDashboardData from "../dashboard/getDashboardData.js";
import type * as debug_checkOrientationStatus from "../debug/checkOrientationStatus.js";
import type * as debug_resetApplicationForTest from "../debug/resetApplicationForTest.js";
import type * as documentTypes_list from "../documentTypes/list.js";
import type * as documentUploads_get from "../documentUploads/get.js";
import type * as documentUploads_getReviewedDocumentsWithDetails from "../documentUploads/getReviewedDocumentsWithDetails.js";
import type * as documentUploads_getStorageFileIdAction from "../documentUploads/getStorageFileIdAction.js";
import type * as documentUploads_getStorageFileIdByUploadId from "../documentUploads/getStorageFileIdByUploadId.js";
import type * as documents_classifyDocument from "../documents/classifyDocument.js";
import type * as documents_documentAccessLogs from "../documents/documentAccessLogs.js";
import type * as documents_documentQueries from "../documents/documentQueries.js";
import type * as documents_getReferralCount from "../documents/getReferralCount.js";
import type * as documents_hmacUtils from "../documents/hmacUtils.js";
import type * as documents_referralQueries from "../documents/referralQueries.js";
import type * as documents_rejectionQueries from "../documents/rejectionQueries.js";
import type * as documents_secureAccessQueries from "../documents/secureAccessQueries.js";
import type * as documents_triggerClassification from "../documents/triggerClassification.js";
import type * as documents from "../documents.js";
import type * as healthCards_generateHealthCard from "../healthCards/generateHealthCard.js";
import type * as healthCards_getHealthCard from "../healthCards/getHealthCard.js";
import type * as healthCards_getUserCards from "../healthCards/getUserCards.js";
import type * as healthCards_issueHealthCard from "../healthCards/issueHealthCard.js";
import type * as healthCards_regenerateHealthCard from "../healthCards/regenerateHealthCard.js";
import type * as healthCards_updateHealthCard from "../healthCards/updateHealthCard.js";
import type * as http from "../http.js";
import type * as jobCategories_createJobCategory from "../jobCategories/createJobCategory.js";
import type * as jobCategories_deleteJobCategory from "../jobCategories/deleteJobCategory.js";
import type * as jobCategories_getAllJobCategories from "../jobCategories/getAllJobCategories.js";
import type * as jobCategories_getManaged from "../jobCategories/getManaged.js";
import type * as jobCategories_updateJobCategory from "../jobCategories/updateJobCategory.js";
import type * as labFindings_index from "../labFindings/index.js";
import type * as labFindings_referenceData from "../labFindings/referenceData.js";
import type * as lib_documentStatus from "../lib/documentStatus.js";
import type * as lib_serverTime from "../lib/serverTime.js";
import type * as lib_sessionStatus from "../lib/sessionStatus.js";
import type * as lib_timezone from "../lib/timezone.js";
import type * as migrations_backfillServiceFees from "../migrations/backfillServiceFees.js";
import type * as migrations_migrateToSystemAdmin from "../migrations/migrateToSystemAdmin.js";
import type * as migrations_updateLockedApplicationStatus from "../migrations/updateLockedApplicationStatus.js";
import type * as notifications from "../notifications.js";
import type * as ocr_extractDocumentText from "../ocr/extractDocumentText.js";
import type * as ocr_saveExtractedText from "../ocr/saveExtractedText.js";
import type * as orientationSchedules from "../orientationSchedules.js";
import type * as orientations_attendance from "../orientations/attendance.js";
import type * as orientations_getUserOrientations from "../orientations/getUserOrientations.js";
import type * as orientations_index from "../orientations/index.js";
import type * as orientations_queries from "../orientations/queries.js";
import type * as orientations from "../orientations.js";
import type * as payments_createPayment from "../payments/createPayment.js";
import type * as payments_getAllPayments from "../payments/getAllPayments.js";
import type * as payments_getForApplication from "../payments/getForApplication.js";
import type * as payments_getPaymentByApplication from "../payments/getPaymentByApplication.js";
import type * as payments_getPaymentByFormId from "../payments/getPaymentByFormId.js";
import type * as payments_getPaymentHistory from "../payments/getPaymentHistory.js";
import type * as payments_getRejectionHistory from "../payments/getRejectionHistory.js";
import type * as payments_getUserPayments from "../payments/getUserPayments.js";
import type * as payments_handleRedirectSuccess from "../payments/handleRedirectSuccess.js";
import type * as payments_maya_abandonedPayments from "../payments/maya/abandonedPayments.js";
import type * as payments_maya_checkout from "../payments/maya/checkout.js";
import type * as payments_maya_client from "../payments/maya/client.js";
import type * as payments_maya_constants from "../payments/maya/constants.js";
import type * as payments_maya_handleReturn from "../payments/maya/handleReturn.js";
import type * as payments_maya_statusUpdates from "../payments/maya/statusUpdates.js";
import type * as payments_maya_types from "../payments/maya/types.js";
import type * as payments_maya_webhook from "../payments/maya/webhook.js";
import type * as payments_resubmitPayment from "../payments/resubmitPayment.js";
import type * as payments_updatePaymentStatus from "../payments/updatePaymentStatus.js";
import type * as requirements_adminBatchReviewDocuments from "../requirements/adminBatchReviewDocuments.js";
import type * as requirements_adminGetDocumentsByStatus from "../requirements/adminGetDocumentsByStatus.js";
import type * as requirements_adminGetPendingDocuments from "../requirements/adminGetPendingDocuments.js";
import type * as requirements_adminReviewDocument from "../requirements/adminReviewDocument.js";
import type * as requirements_createJobCategoryRequirement from "../requirements/createJobCategoryRequirement.js";
import type * as requirements_deleteStorageFile from "../requirements/deleteStorageFile.js";
import type * as requirements_getDocumentUrl from "../requirements/getDocumentUrl.js";
import type * as requirements_getFormDocumentsRequirements from "../requirements/getFormDocumentsRequirements.js";
import type * as requirements_getJobCategoryRequirements from "../requirements/getJobCategoryRequirements.js";
import type * as requirements_getRequirementsByJobCategory from "../requirements/getRequirementsByJobCategory.js";
import type * as requirements_removeDocument from "../requirements/removeDocument.js";
import type * as requirements_removeJobCategoryRequirement from "../requirements/removeJobCategoryRequirement.js";
import type * as requirements_resubmitDocument from "../requirements/resubmitDocument.js";
import type * as requirements_updateDocumentField from "../requirements/updateDocumentField.js";
import type * as requirements_updateJobCategoryRequirement from "../requirements/updateJobCategoryRequirement.js";
import type * as requirements_uploadDocuments from "../requirements/uploadDocuments.js";
import type * as signatures_uploadSignatures from "../signatures/uploadSignatures.js";
import type * as storage_generateUploadUrl from "../storage/generateUploadUrl.js";
import type * as superAdmin_mutations from "../superAdmin/mutations.js";
import type * as superAdmin_queries from "../superAdmin/queries.js";
import type * as systemConfig_index from "../systemConfig/index.js";
import type * as users_createUser from "../users/createUser.js";
import type * as users_getApplicants from "../users/getApplicants.js";
import type * as users_getCurrentUser from "../users/getCurrentUser.js";
import type * as users_getUsersByRole from "../users/getUsersByRole.js";
import type * as users_index from "../users/index.js";
import type * as users_permissions from "../users/permissions.js";
import type * as users_roles from "../users/roles.js";
import type * as users_updateRole from "../users/updateRole.js";
import type * as users_updateUser from "../users/updateUser.js";
import type * as users_updateUserDb from "../users/updateUserDb.js";
import type * as users_userQueries from "../users/userQueries.js";
import type * as verification_createVerificationLog from "../verification/createVerificationLog.js";
import type * as verification_getVerificationLogsByHealthCard from "../verification/getVerificationLogsByHealthCard.js";
import type * as verification_getVerificationLogsByUser from "../verification/getVerificationLogsByUser.js";
import type * as verification_getVerificationStats from "../verification/getVerificationStats.js";
import type * as verification_logQRScan from "../verification/logQRScan.js";
import type * as verification_logVerificationAttempt from "../verification/logVerificationAttempt.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "_notifications/clearReadNotifications": typeof _notifications_clearReadNotifications;
  "_notifications/createNotification": typeof _notifications_createNotification;
  "_notifications/getAdminNotifications": typeof _notifications_getAdminNotifications;
  "_notifications/getNotificationById": typeof _notifications_getNotificationById;
  "_notifications/getNotificationWithDetails": typeof _notifications_getNotificationWithDetails;
  "_notifications/getPaymentRejectionNotifications": typeof _notifications_getPaymentRejectionNotifications;
  "_notifications/getReferralHistoryNotifications": typeof _notifications_getReferralHistoryNotifications;
  "_notifications/getRejectionHistoryNotifications": typeof _notifications_getRejectionHistoryNotifications;
  "_notifications/getUnreadCount": typeof _notifications_getUnreadCount;
  "_notifications/getUserNotifications": typeof _notifications_getUserNotifications;
  "_notifications/markAllAsRead": typeof _notifications_markAllAsRead;
  "_notifications/markAllNotificationsAsRead": typeof _notifications_markAllNotificationsAsRead;
  "_notifications/markAsRead": typeof _notifications_markAsRead;
  "_notifications/markNotificationAsRead": typeof _notifications_markNotificationAsRead;
  "_notifications/markReferralHistoryAsRead": typeof _notifications_markReferralHistoryAsRead;
  "_notifications/markRejectionHistoryAsRead": typeof _notifications_markRejectionHistoryAsRead;
  "_notifications/sendAdminNotification": typeof _notifications_sendAdminNotification;
  "_orientationSchedules/autoCreateSchedulesHandler": typeof _orientationSchedules_autoCreateSchedulesHandler;
  "_orientationSchedules/bookOrientationSlot": typeof _orientationSchedules_bookOrientationSlot;
  "_orientationSchedules/cancelOrientationBooking": typeof _orientationSchedules_cancelOrientationBooking;
  "_orientationSchedules/debugListAll": typeof _orientationSchedules_debugListAll;
  "_orientationSchedules/fixScheduleDates": typeof _orientationSchedules_fixScheduleDates;
  "_orientationSchedules/getAvailableSchedules": typeof _orientationSchedules_getAvailableSchedules;
  "_orientationSchedules/getSchedulesForDate": typeof _orientationSchedules_getSchedulesForDate;
  "_orientationSchedules/getUserOrientationSession": typeof _orientationSchedules_getUserOrientationSession;
  "_orientationSchedules/migrateTimeFields": typeof _orientationSchedules_migrateTimeFields;
  "_orientationSchedules/migrateToPhilippineTime": typeof _orientationSchedules_migrateToPhilippineTime;
  "_orientationSchedules/mutations": typeof _orientationSchedules_mutations;
  "_orientationSchedules/queries": typeof _orientationSchedules_queries;
  "_orientationSchedules/seedOrientationSchedules": typeof _orientationSchedules_seedOrientationSchedules;
  "_orientationSchedules/timeUtils": typeof _orientationSchedules_timeUtils;
  "admin/activityLogs": typeof admin_activityLogs;
  "admin/adminMain": typeof admin_adminMain;
  "admin/documents/referDocument": typeof admin_documents_referDocument;
  "admin/documents/rejectDocument": typeof admin_documents_rejectDocument;
  "admin/documents/sendReferralNotifications": typeof admin_documents_sendReferralNotifications;
  "admin/documents/sendRejectionNotifications": typeof admin_documents_sendRejectionNotifications;
  "admin/finalizeApplication": typeof admin_finalizeApplication;
  "admin/fixFoodHandlerWorkflow": typeof admin_fixFoodHandlerWorkflow;
  "admin/fixJobCategoryDocuments": typeof admin_fixJobCategoryDocuments;
  "admin/inspectorAvailability": typeof admin_inspectorAvailability;
  "admin/migrations/fixRejectionStatus": typeof admin_migrations_fixRejectionStatus;
  "admin/orientation": typeof admin_orientation;
  "admin/payments/rejectPayment": typeof admin_payments_rejectPayment;
  "admin/payments/testResubmission": typeof admin_payments_testResubmission;
  "admin/rejectApplicationFinal": typeof admin_rejectApplicationFinal;
  "admin/rejectionHistory": typeof admin_rejectionHistory;
  "admin/reviewDocument": typeof admin_reviewDocument;
  "admin/seed": typeof admin_seed;
  "admin/testFixRejectionStatus": typeof admin_testFixRejectionStatus;
  "admin/updateAdminAccount": typeof admin_updateAdminAccount;
  "admin/updateAdminAccountInternal": typeof admin_updateAdminAccountInternal;
  "admin/validatePayment": typeof admin_validatePayment;
  "applications/autoCancelExpiredApplications": typeof applications_autoCancelExpiredApplications;
  "applications/checkRenewalEligibility": typeof applications_checkRenewalEligibility;
  "applications/createApplication": typeof applications_createApplication;
  "applications/createForm": typeof applications_createForm;
  "applications/createRenewalApplication": typeof applications_createRenewalApplication;
  "applications/deleteApplication": typeof applications_deleteApplication;
  "applications/getApplicationById": typeof applications_getApplicationById;
  "applications/getDocumentsWithClassification": typeof applications_getDocumentsWithClassification;
  "applications/getFormById": typeof applications_getFormById;
  "applications/getPreviousApplicationData": typeof applications_getPreviousApplicationData;
  "applications/getUserApplications": typeof applications_getUserApplications;
  "applications/getWithDocuments": typeof applications_getWithDocuments;
  "applications/lib/renewalEligibility": typeof applications_lib_renewalEligibility;
  "applications/list": typeof applications_list;
  "applications/submitApplication": typeof applications_submitApplication;
  "applications/updateApplication": typeof applications_updateApplication;
  "applications/updateApplicationStatus": typeof applications_updateApplicationStatus;
  "config/barangays": typeof config_barangays;
  "config/paymentConstants": typeof config_paymentConstants;
  "config/rejectionLimits": typeof config_rejectionLimits;
  crons: typeof crons;
  "dashboard/getActivityLog": typeof dashboard_getActivityLog;
  "dashboard/getDashboardData": typeof dashboard_getDashboardData;
  "debug/checkOrientationStatus": typeof debug_checkOrientationStatus;
  "debug/resetApplicationForTest": typeof debug_resetApplicationForTest;
  "documentTypes/list": typeof documentTypes_list;
  "documentUploads/get": typeof documentUploads_get;
  "documentUploads/getReviewedDocumentsWithDetails": typeof documentUploads_getReviewedDocumentsWithDetails;
  "documentUploads/getStorageFileIdAction": typeof documentUploads_getStorageFileIdAction;
  "documentUploads/getStorageFileIdByUploadId": typeof documentUploads_getStorageFileIdByUploadId;
  "documents/classifyDocument": typeof documents_classifyDocument;
  "documents/documentAccessLogs": typeof documents_documentAccessLogs;
  "documents/documentQueries": typeof documents_documentQueries;
  "documents/getReferralCount": typeof documents_getReferralCount;
  "documents/hmacUtils": typeof documents_hmacUtils;
  "documents/referralQueries": typeof documents_referralQueries;
  "documents/rejectionQueries": typeof documents_rejectionQueries;
  "documents/secureAccessQueries": typeof documents_secureAccessQueries;
  "documents/triggerClassification": typeof documents_triggerClassification;
  documents: typeof documents;
  "healthCards/generateHealthCard": typeof healthCards_generateHealthCard;
  "healthCards/getHealthCard": typeof healthCards_getHealthCard;
  "healthCards/getUserCards": typeof healthCards_getUserCards;
  "healthCards/issueHealthCard": typeof healthCards_issueHealthCard;
  "healthCards/regenerateHealthCard": typeof healthCards_regenerateHealthCard;
  "healthCards/updateHealthCard": typeof healthCards_updateHealthCard;
  http: typeof http;
  "jobCategories/createJobCategory": typeof jobCategories_createJobCategory;
  "jobCategories/deleteJobCategory": typeof jobCategories_deleteJobCategory;
  "jobCategories/getAllJobCategories": typeof jobCategories_getAllJobCategories;
  "jobCategories/getManaged": typeof jobCategories_getManaged;
  "jobCategories/updateJobCategory": typeof jobCategories_updateJobCategory;
  "labFindings/index": typeof labFindings_index;
  "labFindings/referenceData": typeof labFindings_referenceData;
  "lib/documentStatus": typeof lib_documentStatus;
  "lib/serverTime": typeof lib_serverTime;
  "lib/sessionStatus": typeof lib_sessionStatus;
  "lib/timezone": typeof lib_timezone;
  "migrations/backfillServiceFees": typeof migrations_backfillServiceFees;
  "migrations/migrateToSystemAdmin": typeof migrations_migrateToSystemAdmin;
  "migrations/updateLockedApplicationStatus": typeof migrations_updateLockedApplicationStatus;
  notifications: typeof notifications;
  "ocr/extractDocumentText": typeof ocr_extractDocumentText;
  "ocr/saveExtractedText": typeof ocr_saveExtractedText;
  orientationSchedules: typeof orientationSchedules;
  "orientations/attendance": typeof orientations_attendance;
  "orientations/getUserOrientations": typeof orientations_getUserOrientations;
  "orientations/index": typeof orientations_index;
  "orientations/queries": typeof orientations_queries;
  orientations: typeof orientations;
  "payments/createPayment": typeof payments_createPayment;
  "payments/getAllPayments": typeof payments_getAllPayments;
  "payments/getForApplication": typeof payments_getForApplication;
  "payments/getPaymentByApplication": typeof payments_getPaymentByApplication;
  "payments/getPaymentByFormId": typeof payments_getPaymentByFormId;
  "payments/getPaymentHistory": typeof payments_getPaymentHistory;
  "payments/getRejectionHistory": typeof payments_getRejectionHistory;
  "payments/getUserPayments": typeof payments_getUserPayments;
  "payments/handleRedirectSuccess": typeof payments_handleRedirectSuccess;
  "payments/maya/abandonedPayments": typeof payments_maya_abandonedPayments;
  "payments/maya/checkout": typeof payments_maya_checkout;
  "payments/maya/client": typeof payments_maya_client;
  "payments/maya/constants": typeof payments_maya_constants;
  "payments/maya/handleReturn": typeof payments_maya_handleReturn;
  "payments/maya/statusUpdates": typeof payments_maya_statusUpdates;
  "payments/maya/types": typeof payments_maya_types;
  "payments/maya/webhook": typeof payments_maya_webhook;
  "payments/resubmitPayment": typeof payments_resubmitPayment;
  "payments/updatePaymentStatus": typeof payments_updatePaymentStatus;
  "requirements/adminBatchReviewDocuments": typeof requirements_adminBatchReviewDocuments;
  "requirements/adminGetDocumentsByStatus": typeof requirements_adminGetDocumentsByStatus;
  "requirements/adminGetPendingDocuments": typeof requirements_adminGetPendingDocuments;
  "requirements/adminReviewDocument": typeof requirements_adminReviewDocument;
  "requirements/createJobCategoryRequirement": typeof requirements_createJobCategoryRequirement;
  "requirements/deleteStorageFile": typeof requirements_deleteStorageFile;
  "requirements/getDocumentUrl": typeof requirements_getDocumentUrl;
  "requirements/getFormDocumentsRequirements": typeof requirements_getFormDocumentsRequirements;
  "requirements/getJobCategoryRequirements": typeof requirements_getJobCategoryRequirements;
  "requirements/getRequirementsByJobCategory": typeof requirements_getRequirementsByJobCategory;
  "requirements/removeDocument": typeof requirements_removeDocument;
  "requirements/removeJobCategoryRequirement": typeof requirements_removeJobCategoryRequirement;
  "requirements/resubmitDocument": typeof requirements_resubmitDocument;
  "requirements/updateDocumentField": typeof requirements_updateDocumentField;
  "requirements/updateJobCategoryRequirement": typeof requirements_updateJobCategoryRequirement;
  "requirements/uploadDocuments": typeof requirements_uploadDocuments;
  "signatures/uploadSignatures": typeof signatures_uploadSignatures;
  "storage/generateUploadUrl": typeof storage_generateUploadUrl;
  "superAdmin/mutations": typeof superAdmin_mutations;
  "superAdmin/queries": typeof superAdmin_queries;
  "systemConfig/index": typeof systemConfig_index;
  "users/createUser": typeof users_createUser;
  "users/getApplicants": typeof users_getApplicants;
  "users/getCurrentUser": typeof users_getCurrentUser;
  "users/getUsersByRole": typeof users_getUsersByRole;
  "users/index": typeof users_index;
  "users/permissions": typeof users_permissions;
  "users/roles": typeof users_roles;
  "users/updateRole": typeof users_updateRole;
  "users/updateUser": typeof users_updateUser;
  "users/updateUserDb": typeof users_updateUserDb;
  "users/userQueries": typeof users_userQueries;
  "verification/createVerificationLog": typeof verification_createVerificationLog;
  "verification/getVerificationLogsByHealthCard": typeof verification_getVerificationLogsByHealthCard;
  "verification/getVerificationLogsByUser": typeof verification_getVerificationLogsByUser;
  "verification/getVerificationStats": typeof verification_getVerificationStats;
  "verification/logQRScan": typeof verification_logQRScan;
  "verification/logVerificationAttempt": typeof verification_logVerificationAttempt;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
