import { StyleSheet } from 'react-native';
import { getBorderRadius, getColor, getShadow, getSpacing, getTypography } from '../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: getColor('background.secondary'),
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: getSpacing('lg'),
    paddingVertical: getSpacing('md'),
    backgroundColor: getColor('background.primary'),
    borderBottomWidth: 1,
    borderBottomColor: getColor('border.light'),
  },
  headerTitle: {
    ...getTypography('h2'),
    color: getColor('text.primary'),
  },
  scrollView: {
    flex: 1,
  },
  contextContainer: {
    backgroundColor: getColor('background.primary'),
    marginHorizontal: getSpacing('lg'),
    marginTop: getSpacing('lg'),
    borderRadius: getBorderRadius('lg'),
    padding: getSpacing('lg'),
    ...getShadow('medium'),
  },
  contextTitle: {
    ...getTypography('body'),
    fontWeight: '600',
    color: getColor('text.primary'),
    marginBottom: getSpacing('md'),
  },
  contextDetails: {
    gap: getSpacing('sm'),
  },
  contextLabel: {
    ...getTypography('body'),
    color: getColor('text.secondary'),
  },
  contextValue: {
    ...getTypography('body'),
    color: getColor('text.primary'),
    fontWeight: '600',
  },
  instructionsContainer: {
    flexDirection: 'row',
    padding: getSpacing('lg'),
    backgroundColor: getColor('primary.light'),
    marginHorizontal: getSpacing('lg'),
    marginTop: getSpacing('lg'),
    borderRadius: getBorderRadius('lg'),
  },
  instructionsText: {
    flex: 1,
    marginLeft: getSpacing('sm'),
  },
  instructionsTitle: {
    ...getTypography('body'),
    fontWeight: '600',
    color: getColor('primary.main'),
    marginBottom: getSpacing('xs'),
  },
  instructionsSubtitle: {
    ...getTypography('body'),
    color: getColor('primary.main'),
    lineHeight: 20,
  },
  instructionsNote: {
    ...getTypography('bodySmall'),
    color: getColor('primary.main'),
    lineHeight: 16,
    marginTop: getSpacing('sm'),
    fontStyle: 'italic',
  },
  documentUploader: {
    paddingHorizontal: getSpacing('lg'),
    paddingTop: getSpacing('lg'),
  },
  documentsContainer: {
    paddingHorizontal: getSpacing('lg'),
    paddingTop: getSpacing('lg'),
  },
  documentCard: {
    backgroundColor: getColor('background.primary'),
    borderRadius: getBorderRadius('lg'),
    padding: getSpacing('md'),
    marginBottom: getSpacing('md'),
    ...getShadow('medium'),
  },
  documentHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: getSpacing('sm'),
  },
  documentInfo: {
    flex: 1,
  },
  documentName: {
    ...getTypography('body'),
    fontWeight: '600',
    color: getColor('text.primary'),
    marginBottom: getSpacing('xs'),
  },
  requiredMark: {
    color: getColor('error.main'),
  },
  documentDescription: {
    ...getTypography('body'),
    color: getColor('text.secondary'),
    marginBottom: getSpacing('xs'),
  },
  documentFormats: {
    ...getTypography('bodySmall'),
    color: getColor('text.secondary'),
    fontStyle: 'italic',
  },
  documentStatus: {
    marginLeft: getSpacing('sm'),
  },
  progressContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: getSpacing('sm'),
  },
  progressBar: {
    flex: 1,
    height: 4,
    backgroundColor: getColor('border.light'),
    borderRadius: getBorderRadius('xs'),
    marginRight: getSpacing('sm'),
  },
  progressFill: {
    height: '100%',
    backgroundColor: getColor('primary.main'),
    borderRadius: getBorderRadius('xs'),
  },
  progressText: {
    ...getTypography('bodySmall'),
    color: getColor('text.secondary'),
    minWidth: 35,
  },
  documentPreview: {
    position: 'relative',
    marginBottom: getSpacing('sm'),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: getSpacing('sm'),
    backgroundColor: getColor('background.secondary'),
    borderRadius: getBorderRadius('sm'),
  },
  previewImage: {
    width: '100%',
    height: 120,
    borderRadius: getBorderRadius('sm'),
    backgroundColor: getColor('background.secondary'),
  },
  removeButton: {
    backgroundColor: getColor('background.primary'),
    borderRadius: getBorderRadius('sm'),
    padding: getSpacing('xs'),
  },
  documentActions: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  uploadButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: getSpacing('lg'),
    paddingVertical: getSpacing('sm'),
    borderRadius: getBorderRadius('sm'),
    borderWidth: 1,
    borderColor: getColor('primary.main'),
    backgroundColor: getColor('background.primary'),
  },
  uploadButtonText: {
    ...getTypography('body'),
    color: getColor('primary.main'),
    fontWeight: '600',
    marginLeft: getSpacing('sm'),
  },
  submitContainer: {
    paddingHorizontal: getSpacing('lg'),
    paddingVertical: getSpacing('lg'),
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: getColor('background.primary'),
    borderTopLeftRadius: getBorderRadius('xl'),
    borderTopRightRadius: getBorderRadius('xl'),
    padding: getSpacing('lg'),
  },
  modalTitle: {
    ...getTypography('h3'),
    color: getColor('text.primary'),
    textAlign: 'center',
    marginBottom: getSpacing('lg'),
  },
  modalOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: getSpacing('md'),
    paddingHorizontal: getSpacing('lg'),
    borderRadius: getBorderRadius('lg'),
    backgroundColor: getColor('background.secondary'),
    marginBottom: getSpacing('sm'),
  },
  modalOptionText: {
    ...getTypography('body'),
    color: getColor('text.primary'),
    marginLeft: getSpacing('md'),
  },
  modalCancelButton: {
    paddingVertical: getSpacing('md'),
    alignItems: 'center',
  },
  modalCancelText: {
    ...getTypography('body'),
    color: getColor('error.main'),
    fontWeight: '600',
  },
  errorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: getColor('error.light'),
    padding: getSpacing('sm'),
    borderRadius: getBorderRadius('sm'),
    marginBottom: getSpacing('sm'),
  },
  errorText: {
    ...getTypography('bodySmall'),
    color: getColor('error.main'),
    flex: 1,
    marginLeft: getSpacing('xs'),
  },
  retryButton: {
    paddingHorizontal: getSpacing('sm'),
    paddingVertical: getSpacing('xs'),
    borderRadius: getBorderRadius('xs'),
    backgroundColor: getColor('error.main'),
    marginLeft: getSpacing('sm'),
  },
  retryButtonText: {
    ...getTypography('bodySmall'),
    color: getColor('background.primary'),
    fontWeight: '600',
  },
});