import { StyleSheet } from 'react-native';
import { theme } from '@shared/styles/theme';
import { moderateScale, verticalScale, scale } from '@shared/utils/responsive';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background.secondary,
  },
  scrollView: {
    flex: 1,
  },
  scrollViewContent: {
    paddingTop: verticalScale(theme.spacing.sm),
    paddingBottom: verticalScale(theme.spacing.xl * 1),
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.colors.background.primary,
  },
  loadingText: {
    fontSize: moderateScale(16),
    color: theme.colors.text.secondary,
    marginTop: verticalScale(theme.spacing.md),
  },

  // Status Card - Updated to match profile card style
  statusCard: {
    backgroundColor: theme.colors.background.primary,
    marginHorizontal: scale(16),
    marginTop: verticalScale(16),
    marginBottom: verticalScale(16),
    borderRadius: moderateScale(12),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  statusHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: scale(16),
    paddingTop: verticalScale(16),
    paddingBottom: verticalScale(8),
  },
  statusHeaderWithId: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: scale(16),
    paddingTop: verticalScale(16),
    paddingBottom: verticalScale(12),
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: verticalScale(theme.spacing.xs),
    paddingHorizontal: scale(theme.spacing.sm),
    borderRadius: theme.borderRadius.full,
    gap: scale(theme.spacing.xs),
    maxWidth: '100%',
    flexShrink: 1,
  },
  statusInfo: {
    paddingHorizontal: scale(16),
    paddingBottom: verticalScale(16),
  },
  statusLabel: {
    fontSize: moderateScale(12),
    color: theme.colors.text.secondary,
    marginBottom: verticalScale(theme.spacing.xs),
  },
  statusValue: {
    fontSize: moderateScale(14),
    color: theme.colors.text.primary,
    fontWeight: '500' as const,
  },
  statusText: {
    fontSize: moderateScale(13),
    fontWeight: '600' as const,
    flexShrink: 1,
  },
  applicationId: {
    fontSize: moderateScale(12),
    color: theme.colors.text.secondary,
  },
  deadlineContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: verticalScale(theme.spacing.md),
    padding: moderateScale(theme.spacing.sm),
    backgroundColor: theme.colors.background.tertiary,
    borderRadius: theme.borderRadius.md,
    gap: scale(theme.spacing.xs),
  },
  deadlineText: {
    fontSize: moderateScale(13),
    fontWeight: '500' as const,
  },
  urgencyBanner: {
    padding: moderateScale(theme.spacing.sm),
    borderRadius: theme.borderRadius.md,
    marginBottom: verticalScale(theme.spacing.md),
  },
  urgencyText: {
    fontSize: moderateScale(14),
    fontWeight: '600' as const,
    textAlign: 'center',
  },
  remarksContainer: {
    backgroundColor: theme.colors.background.tertiary,
    padding: moderateScale(theme.spacing.md),
    borderRadius: theme.borderRadius.md,
  },
  remarksLabel: {
    fontSize: moderateScale(14),
    fontWeight: '600' as const,
    color: theme.colors.text.secondary,
    marginBottom: verticalScale(theme.spacing.xs),
  },
  remarksText: {
    fontSize: moderateScale(14),
    color: theme.colors.text.primary,
    lineHeight: moderateScale(14 * 1.5),
    paddingTop: verticalScale(8),
  },

  // Details Card - Updated to match profile card style
  detailsCard: {
    backgroundColor: theme.colors.background.primary,
    marginHorizontal: scale(16),
    marginBottom: verticalScale(16),
    borderRadius: moderateScale(12),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: scale(16),
    paddingVertical: verticalScale(14),
    borderTopWidth: moderateScale(1),
    borderTopColor: '#F0F0F0',
  },
  detailLabel: {
    fontSize: moderateScale(14),
    color: theme.colors.text.secondary,
    flex: 1,
  },
  detailValue: {
    fontSize: moderateScale(14),
    color: theme.colors.text.primary,
    fontWeight: '500' as const,
    flex: 2,
    textAlign: 'right',
  },
  categoryContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    flex: 2,
    gap: scale(theme.spacing.xs),
  },
  categoryIndicator: {
    width: moderateScale(12),
    height: moderateScale(12),
    borderRadius: theme.borderRadius.full,
  },

  sectionTitle: {
    fontSize: moderateScale(12),
    fontWeight: '600' as const,
    color: '#999',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    paddingHorizontal: scale(16),
    paddingTop: verticalScale(16),
    paddingBottom: verticalScale(12),
  },
  collapsibleHeader: {
    // No padding needed, sectionTitle has its own
  },
  expandButton: {
    position: 'relative',
    alignItems: 'center',
    paddingVertical: verticalScale(12),
    paddingBottom: verticalScale(16),
    borderBottomLeftRadius: moderateScale(12),
    borderBottomRightRadius: moderateScale(12),
  },
  expandButtonShadow: {
    position: 'absolute',
    top: -30,
    left: 0,
    right: 0,
    height: 30,
    backgroundColor: 'transparent',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
  },
  collapseButton: {
    alignItems: 'center',
    paddingVertical: verticalScale(12),
    paddingBottom: verticalScale(16),
    borderBottomLeftRadius: moderateScale(12),
    borderBottomRightRadius: moderateScale(12),
    borderTopWidth: moderateScale(1),
    borderTopColor: '#F0F0F0',
  },
  collapseButtonExternal: {
    alignItems: 'center',
    paddingVertical: verticalScale(12),
    marginHorizontal: scale(16),
    marginTop: verticalScale(-8), // Bring it closer to the card
    marginBottom: verticalScale(8),
  },
  fadedText: {
    opacity: 0.35,
  },
  fadedRow: {
    opacity: 0.35,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: verticalScale(theme.spacing.sm),
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border.light + '30',
  },
  infoLabel: {
    fontSize: moderateScale(14),
    color: theme.colors.text.secondary,
    flex: 1,
  },
  infoValue: {
    fontSize: moderateScale(14),
    color: theme.colors.text.primary,
    fontWeight: '500' as const,
    flex: 2,
    textAlign: 'right',
  },
  jobCategoryBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    flex: 2,
  },
  jobCategoryDot: {
    width: moderateScale(10),
    height: moderateScale(10),
    borderRadius: theme.borderRadius.full,
    marginRight: scale(theme.spacing.xs),
  },

  // Orientation Card - Similar to documents card
  orientationCard: {
    backgroundColor: theme.colors.background.primary,
    marginHorizontal: scale(16),
    marginBottom: verticalScale(16),
    borderRadius: moderateScale(12),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },

  // Payment Card - Compact design matching profile card style
  paymentCard: {
    backgroundColor: theme.colors.background.primary,
    marginHorizontal: scale(16),
    marginBottom: verticalScale(16),
    borderRadius: moderateScale(12),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  paymentDescription: {
    fontSize: moderateScale(14),
    color: theme.colors.text.secondary,
    marginBottom: verticalScale(theme.spacing.md),
    paddingHorizontal: scale(16),
  },
  feeBreakdown: {
    backgroundColor: theme.colors.background.tertiary,
    marginHorizontal: scale(16),
    padding: moderateScale(theme.spacing.md),
    borderRadius: theme.borderRadius.md,
    marginBottom: verticalScale(theme.spacing.lg),
  },
  feeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: verticalScale(theme.spacing.xs),
  },
  feeLabel: {
    fontSize: moderateScale(14),
    color: theme.colors.text.secondary,
  },
  feeValue: {
    fontSize: moderateScale(14),
    color: theme.colors.text.primary,
    fontWeight: '500' as const,
  },
  totalRow: {
    borderTopWidth: 1,
    borderTopColor: theme.colors.border.light,
    marginTop: verticalScale(theme.spacing.xs),
    paddingTop: verticalScale(theme.spacing.sm),
  },
  totalLabel: {
    fontSize: moderateScale(16),
    color: theme.colors.text.primary,
    fontWeight: '600' as const,
  },
  totalValue: {
    fontSize: moderateScale(16),
    color: theme.colors.primary[500],
    fontWeight: '700' as const,
  },
  paymentMethodsTitle: {
    fontSize: moderateScale(14),
    fontWeight: '600' as const,
    color: theme.colors.text.primary,
    marginBottom: verticalScale(theme.spacing.xs),
    paddingHorizontal: scale(16),
  },
  paymentMethodsSubtitle: {
    fontSize: moderateScale(12),
    color: theme.colors.text.secondary,
    marginBottom: verticalScale(theme.spacing.md),
    paddingHorizontal: scale(16),
  },
  paymentSection: {
    marginBottom: verticalScale(theme.spacing.md),
  },
  paymentSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: scale(16),
    paddingVertical: verticalScale(8),
    gap: scale(8),
    backgroundColor: theme.colors.background.tertiary,
    marginHorizontal: scale(16),
    borderRadius: theme.borderRadius.sm,
    marginBottom: verticalScale(8),
  },
  paymentSectionTitle: {
    fontSize: moderateScale(13),
    fontWeight: '600' as const,
    color: theme.colors.text.primary,
  },
  paymentMethods: {
    flexDirection: 'column',
    gap: moderateScale(12),
    paddingHorizontal: scale(16),
    paddingBottom: verticalScale(16),
  },
  paymentMethodCard: {
    width: '100%',
    backgroundColor: theme.colors.background.primary,
    padding: moderateScale(16),
    borderRadius: theme.borderRadius.md,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.border.light,
    position: 'relative',
    minHeight: moderateScale(80),
  },
  paymentMethodCardDisabled: {
    opacity: 0.6,
    backgroundColor: theme.colors.background.tertiary,
  },
  paymentMethodIconContainer: {
    width: moderateScale(56),
    height: moderateScale(56),
    borderRadius: theme.borderRadius.md,
    backgroundColor: theme.colors.background.tertiary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: scale(12),
  },
  paymentMethodInfo: {
    flex: 1,
    justifyContent: 'center',
  },
  paymentMethodName: {
    fontSize: moderateScale(15),
    fontWeight: '600' as const,
    color: theme.colors.text.primary,
    marginBottom: verticalScale(4),
  },
  paymentMethodDescription: {
    fontSize: moderateScale(12),
    color: theme.colors.text.secondary,
    lineHeight: moderateScale(16),
  },
  paymentMethodBadge: {
    position: 'absolute',
    top: moderateScale(4),
    right: moderateScale(4),
    backgroundColor: theme.colors.primary[500],
    paddingHorizontal: scale(6),
    paddingVertical: verticalScale(2),
    borderRadius: theme.borderRadius.sm,
  },
  paymentMethodBadgeText: {
    fontSize: moderateScale(8),
    fontWeight: '700' as const,
    color: theme.colors.background.primary,
    letterSpacing: 0.3,
  },
  comingSoonBadge: {
    position: 'absolute',
    top: moderateScale(4),
    right: moderateScale(4),
    backgroundColor: theme.colors.text.secondary + '20',
    paddingHorizontal: scale(6),
    paddingVertical: verticalScale(2),
    borderRadius: theme.borderRadius.sm,
  },
  comingSoonText: {
    fontSize: moderateScale(8),
    fontWeight: '700' as const,
    color: theme.colors.text.secondary,
    letterSpacing: 0.3,
  },
  processingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: verticalScale(theme.spacing.sm),
    paddingVertical: verticalScale(theme.spacing.sm),
    gap: scale(8),
  },
  processingText: {
    fontSize: moderateScale(14),
    color: theme.colors.text.secondary,
  },
  paymentInstructions: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: theme.colors.primary[500] + '10',
    marginHorizontal: scale(16),
    marginTop: verticalScale(theme.spacing.sm),
    marginBottom: verticalScale(theme.spacing.md),
    padding: moderateScale(10),
    borderRadius: theme.borderRadius.sm,
    gap: scale(8),
  },
  paymentInstructionText: {
    flex: 1,
    fontSize: moderateScale(11),
    color: theme.colors.primary[700],
    lineHeight: moderateScale(15),
  },
  
  // Payment History Card - Updated to match profile card style
  paymentHistoryCard: {
    backgroundColor: theme.colors.background.primary,
    marginHorizontal: scale(16),
    marginBottom: verticalScale(16),
    borderRadius: moderateScale(12),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  paymentStatusBadge: {
    paddingHorizontal: scale(10),
    paddingVertical: verticalScale(4),
    borderRadius: theme.borderRadius.full,
  },
  paymentStatusText: {
    fontSize: moderateScale(12),
    fontWeight: '600' as const,
    textTransform: 'capitalize',
  },
  
  // Remarks Card - Updated to match profile card style
  remarksCard: {
    backgroundColor: theme.colors.background.primary,
    marginHorizontal: scale(16),
    marginBottom: verticalScale(16),
    borderRadius: moderateScale(12),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    padding: moderateScale(16),
  },

  // Documents Card - Updated to match profile card style
  documentsCard: {
    backgroundColor: theme.colors.background.primary,
    marginHorizontal: scale(16),
    marginBottom: verticalScale(16),
    borderRadius: moderateScale(12),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  documentsSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: scale(16),
    paddingTop: verticalScale(16),
    paddingBottom: verticalScale(12),
  },
  rejectionBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.semantic.error + '20',
    paddingHorizontal: scale(theme.spacing.sm),
    paddingVertical: verticalScale(theme.spacing.xs),
    borderRadius: theme.borderRadius.full,
    gap: scale(theme.spacing.xs),
  },
  rejectionBadgeText: {
    fontSize: moderateScale(12),
    fontWeight: '600' as const,
    color: theme.colors.semantic.error,
  },
  documentsInfo: {
    flex: 1,
    marginLeft: scale(12),
  },
  documentsStatusText: {
    fontSize: moderateScale(12),
    color: theme.colors.text.secondary,
    marginTop: verticalScale(4),
  },
  viewDocumentsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: scale(16),
    paddingVertical: verticalScale(14),
    borderTopWidth: moderateScale(1),
    borderTopColor: '#F0F0F0',
  },
  viewDocumentsText: {
    fontSize: moderateScale(15),
    color: theme.colors.text.primary,
  },
  documentsIconContainer: {
    width: moderateScale(32),
    height: moderateScale(32),
    borderRadius: moderateScale(16),
    backgroundColor: '#F8F8F8',
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Action Buttons
  actionButtons: {
    paddingHorizontal: scale(theme.spacing.md),
    paddingBottom: verticalScale(theme.spacing.xl),
    gap: verticalScale(theme.spacing.sm),
  },
  // Minimal Inline Header Styles
  inlineHeaderSection: {
    backgroundColor: theme.colors.background.primary,
    paddingTop: verticalScale(12),
    paddingBottom: verticalScale(16),
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: scale(16),
  },
  backButton: {
    width: moderateScale(40),
    height: moderateScale(40),
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: scale(-8), // Align icon to screen edge
    marginRight: scale(12),
  },
  titleContainer: {
    flex: 1,
  },
  pageTitle: {
    fontSize: moderateScale(20),
    fontWeight: '600',
    letterSpacing: -0.3,
    color: theme.colors.text.primary,
  },
  headerSpacer: {
    width: moderateScale(40),
  },
  applicationIdSubtitle: {
    fontSize: moderateScale(14),
    fontWeight: '500',
    color: theme.colors.text.secondary,
    marginTop: verticalScale(4),
  },

  // Payment Rejection Banner Styles
  paymentRejectionBanner: {
    backgroundColor: '#FEF2F2',
    borderLeftWidth: moderateScale(4),
    borderLeftColor: '#DC2626',
    marginHorizontal: scale(16),
    marginVertical: verticalScale(12),
    padding: moderateScale(16),
    borderRadius: theme.borderRadius.md,
    shadowColor: '#DC2626',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  rejectionBannerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: verticalScale(12),
  },
  rejectionIconContainer: {
    width: moderateScale(40),
    height: moderateScale(40),
    borderRadius: moderateScale(20),
    backgroundColor: '#DC2626',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: scale(12),
  },
  rejectionHeaderContent: {
    flex: 1,
  },
  rejectionTitle: {
    fontSize: moderateScale(16),
    fontWeight: '700',
    color: '#991B1B',
    marginBottom: verticalScale(2),
  },
  rejectionAttemptBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#DC2626',
    paddingHorizontal: scale(8),
    paddingVertical: verticalScale(4),
    borderRadius: theme.borderRadius.full,
    marginTop: verticalScale(4),
  },
  rejectionAttemptText: {
    fontSize: moderateScale(11),
    fontWeight: '600',
    color: '#FFFFFF',
  },
  rejectionReasonContainer: {
    backgroundColor: '#FFFFFF',
    padding: moderateScale(12),
    borderRadius: theme.borderRadius.md,
    marginBottom: verticalScale(10),
  },
  rejectionReasonLabel: {
    fontSize: moderateScale(12),
    fontWeight: '600',
    color: '#7F1D1D',
    marginBottom: verticalScale(6),
  },
  rejectionReasonText: {
    fontSize: moderateScale(14),
    color: '#991B1B',
    lineHeight: moderateScale(20),
  },
  rejectionCategoryTag: {
    alignSelf: 'flex-start',
    backgroundColor: '#FCA5A5',
    paddingHorizontal: scale(10),
    paddingVertical: verticalScale(4),
    borderRadius: theme.borderRadius.sm,
    marginBottom: verticalScale(8),
  },
  rejectionCategoryText: {
    fontSize: moderateScale(11),
    fontWeight: '600',
    color: '#7F1D1D',
    textTransform: 'uppercase',
  },
  rejectionIssuesList: {
    marginTop: verticalScale(8),
  },
  rejectionIssueItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: verticalScale(6),
  },
  rejectionIssueBullet: {
    width: moderateScale(6),
    height: moderateScale(6),
    borderRadius: moderateScale(3),
    backgroundColor: '#DC2626',
    marginTop: moderateScale(7),
    marginRight: scale(8),
  },
  rejectionIssueText: {
    flex: 1,
    fontSize: moderateScale(13),
    color: '#991B1B',
    lineHeight: moderateScale(18),
  },
  viewHistoryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    paddingVertical: verticalScale(10),
    paddingHorizontal: scale(14),
    borderRadius: theme.borderRadius.md,
    borderWidth: moderateScale(1),
    borderColor: '#DC2626',
    marginTop: verticalScale(8),
  },
  viewHistoryButtonText: {
    fontSize: moderateScale(13),
    fontWeight: '600',
    color: '#DC2626',
    marginLeft: scale(6),
  },
  resubmitWarningBanner: {
    backgroundColor: '#FEF3C7',
    borderLeftWidth: moderateScale(3),
    borderLeftColor: '#F59E0B',
    padding: moderateScale(12),
    marginHorizontal: scale(16),
    marginBottom: verticalScale(12),
    borderRadius: theme.borderRadius.md,
  },
  resubmitWarningText: {
    fontSize: moderateScale(13),
    color: '#92400E',
    lineHeight: moderateScale(18),
    fontWeight: '500',
  },
});
