import { StyleSheet } from 'react-native';
import { theme } from '@shared/styles/theme';
import { scale, verticalScale, moderateScale } from '@shared/utils/responsive';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background.secondary,
  },
  loadingContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    fontSize: moderateScale(theme.typography.body.fontSize),
    color: theme.colors.text.secondary,
  },
  header: {
    backgroundColor: theme.colors.background.primary,
    borderBottomWidth: moderateScale(1),
    borderBottomColor: theme.colors.border.light,
    paddingHorizontal: scale(theme.spacing.lg),
    paddingTop: verticalScale(theme.spacing.md),
    paddingBottom: verticalScale(theme.spacing.sm),
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: verticalScale(theme.spacing.md),
  },
  headerTitle: {
    fontSize: moderateScale(theme.typography.h2.fontSize),
    fontWeight: theme.typography.h2.fontWeight as any,
    lineHeight: moderateScale(theme.typography.h2.lineHeight),
    color: theme.colors.text.primary,
  },
  markAllButton: {
    paddingHorizontal: scale(theme.spacing.sm),
    paddingVertical: verticalScale(theme.spacing.xs),
    borderRadius: moderateScale(theme.borderRadius.md),
    backgroundColor: theme.colors.brand.primary + '20',
  },
  markAllButtonText: {
    fontSize: moderateScale(theme.typography.bodySmall.fontSize),
    lineHeight: moderateScale(theme.typography.bodySmall.lineHeight),
    color: theme.colors.brand.primary,
    fontWeight: '600',
  },
  filtersContainer: {
    backgroundColor: theme.colors.background.primary,
    paddingHorizontal: scale(theme.spacing.md),
    paddingTop: verticalScale(theme.spacing.md),
    paddingBottom: verticalScale(theme.spacing.sm),
    borderBottomWidth: moderateScale(1),
    borderBottomColor: theme.colors.border.light,
  },
  categoriesContainer: {
    flexDirection: 'row',
  },
  categoryChip: {
    paddingHorizontal: scale(16),
    paddingVertical: verticalScale(10),
    borderRadius: moderateScale(24),
    backgroundColor: theme.colors.background.tertiary,
    marginRight: scale(10),
    borderWidth: 0,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  categoryChipActive: {
    backgroundColor: theme.colors.brand.primary,
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  categoryChipText: {
    fontSize: moderateScale(theme.typography.bodySmall.fontSize),
    lineHeight: moderateScale(theme.typography.bodySmall.lineHeight),
    color: theme.colors.text.secondary,
    fontWeight: '500',
  },
  categoryChipTextActive: {
    color: theme.colors.text.inverse,
  },
  content: {
    flex: 1,
  },
  notificationsList: {
    paddingVertical: verticalScale(theme.spacing.sm),
  },
  dateSection: {
    marginBottom: verticalScale(theme.spacing.md),
  },
  dateLabelContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: scale(theme.spacing.lg),
    marginBottom: verticalScale(theme.spacing.sm),
  },
  dateLabelDivider: {
    flex: 1,
    height: 1,
    backgroundColor: theme.colors.border.light,
  },
  dateLabel: {
    fontSize: moderateScale(11),
    lineHeight: moderateScale(16),
    fontWeight: '600',
    color: theme.colors.text.tertiary,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    paddingHorizontal: scale(12),
    minWidth: scale(70),
  },
  cardsContainer: {
    paddingHorizontal: 0,
  },
  notificationCard: {
    flexDirection: 'row',
    backgroundColor: theme.colors.background.primary,
    borderRadius: moderateScale(16),
    padding: moderateScale(16),
    marginBottom: verticalScale(12),
    width: '92%',
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
    position: 'relative',
    borderWidth: 0,
  },
  notificationCardUnread: {
    backgroundColor: theme.colors.primary[50] || '#F0FDF4',
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 4,
  },
  unreadBadge: {
    position: 'absolute',
    top: moderateScale(12),
    right: moderateScale(12),
    zIndex: 1,
  },
  unreadDot: {
    width: moderateScale(8),
    height: moderateScale(8),
    borderRadius: moderateScale(4),
    backgroundColor: theme.colors.brand.primary,
  },
  notificationIconContainer: {
    width: moderateScale(44),
    height: moderateScale(44),
    borderRadius: moderateScale(22),
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: scale(14),
  },
  notificationContent: {
    flex: 1,
    justifyContent: 'space-between',
  },
  notificationHeader: {
    marginBottom: verticalScale(4),
  },
  notificationTitle: {
    fontSize: moderateScale(15),
    lineHeight: moderateScale(20),
    fontWeight: '600',
    color: theme.colors.text.primary,
    letterSpacing: -0.1,
    marginBottom: verticalScale(2),
  },
  notificationTitleUnread: {
    fontWeight: '700',
    color: theme.colors.text.primary,
  },
  notificationMessage: {
    fontSize: moderateScale(14),
    lineHeight: moderateScale(20),
    color: theme.colors.text.secondary,
    marginBottom: verticalScale(8),
  },
  notificationFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: verticalScale(4),
  },
  timeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  timeIcon: {
    marginRight: scale(theme.spacing.xs),
  },
  notificationTime: {
    fontSize: moderateScale(11),
    lineHeight: moderateScale(15),
    color: '#9CA3AF',
    fontWeight: '500',
  },
  notificationTimestamp: {
    fontSize: moderateScale(10),
    lineHeight: moderateScale(14),
    color: '#9CA3AF',
    fontWeight: '400',
    fontStyle: 'italic',
  },
  // Modern Inline Header Styles
  inlineHeaderSection: {
    backgroundColor: theme.colors.background.primary,
    paddingHorizontal: scale(20),
    paddingTop: verticalScale(12),
    paddingBottom: verticalScale(16),
    marginBottom: verticalScale(8),
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: verticalScale(8),
  },
  titleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(12),
  },
  pageTitle: {
    fontSize: moderateScale(22),
    fontWeight: '600',
    letterSpacing: -0.3,
    color: theme.colors.text.primary,
  },
  headerUnreadBadge: {
    backgroundColor: theme.colors.brand.primary,
    paddingHorizontal: scale(8),
    paddingVertical: verticalScale(2),
    borderRadius: moderateScale(12),
    minWidth: moderateScale(24),
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerUnreadBadgeText: {
    fontSize: moderateScale(12),
    fontWeight: '700',
    color: theme.colors.text.inverse,
  },
  subtitle: {
    fontSize: moderateScale(14),
    fontWeight: '500',
    color: theme.colors.text.secondary,
  },
});
