import { StyleSheet } from "react-native";
import { theme, getShadow } from "@shared/styles/theme";
import { scale, verticalScale, moderateScale } from "@shared/utils/responsive";


export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background.secondary,
  },
  header: {
    backgroundColor: theme.colors.background.primary,
    borderBottomWidth: moderateScale(1),
    borderBottomColor: theme.colors.border.light,
    paddingHorizontal: scale(theme.spacing.lg),
    paddingTop: verticalScale(theme.spacing.md),
    paddingBottom: verticalScale(theme.spacing.sm),
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: verticalScale(theme.spacing.md),
  },
  headerTitle: {
    fontSize: moderateScale(theme.typography.h2.fontSize),
    fontWeight: theme.typography.h2.fontWeight,
    lineHeight: moderateScale(theme.typography.h2.lineHeight),
    color: theme.colors.text.primary,
  },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: scale(theme.spacing.md),
    paddingVertical: verticalScale(theme.spacing.xs),
    borderRadius: theme.borderRadius.full,
    backgroundColor: theme.colors.accent.medicalBlue + '20',
    marginRight: scale(theme.spacing.xs),
    maxWidth: moderateScale(100),
  },
  filterButtonText: {
    fontSize: moderateScale(theme.typography.bodySmall.fontSize),
    lineHeight: moderateScale(theme.typography.bodySmall.lineHeight),
    color: theme.colors.accent.medicalBlue,
    marginLeft: scale(theme.spacing.xs),
    fontWeight: '600',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.background.tertiary,
    borderRadius: theme.borderRadius.lg,
    paddingHorizontal: scale(theme.spacing.sm),
    paddingVertical: verticalScale(theme.spacing.sm),
    marginBottom: verticalScale(theme.spacing.sm),
  },
  searchIcon: {
    marginRight: scale(theme.spacing.sm),
  },
  searchInput: {
    flex: 1,
    fontSize: moderateScale(theme.typography.body.fontSize),
    lineHeight: moderateScale(theme.typography.body.lineHeight),
    color: theme.colors.text.primary,
  },
  filtersContainer: {
    backgroundColor: theme.colors.background.tertiary,
    borderRadius: theme.borderRadius.lg,
    padding: scale(theme.spacing.sm),
    marginBottom: verticalScale(theme.spacing.sm),
  },
  filterSection: {
    marginBottom: verticalScale(theme.spacing.sm),
  },
  filterLabel: {
    fontSize: moderateScale(theme.typography.bodySmall.fontSize),
    lineHeight: moderateScale(theme.typography.bodySmall.lineHeight),
    fontWeight: '600',
    color: theme.colors.text.primary,
    marginBottom: verticalScale(theme.spacing.sm),
  },
  filterChip: {
    paddingHorizontal: scale(theme.spacing.sm),
    paddingVertical: verticalScale(theme.spacing.xs),
    borderRadius: theme.borderRadius.xl,
    backgroundColor: theme.colors.background.primary,
    borderWidth: moderateScale(1),
    borderColor: theme.colors.border.light,
    marginRight: scale(theme.spacing.sm),
  },
  filterChipActive: {
    backgroundColor: theme.colors.accent.medicalBlue,
    borderColor: theme.colors.accent.medicalBlue,
  },
  filterChipText: {
    fontSize: moderateScale(theme.typography.caption.fontSize),
    lineHeight: moderateScale(theme.typography.caption.lineHeight),
    color: theme.colors.text.secondary,
  },
  filterChipTextActive: {
    color: theme.colors.text.inverse,
  },
  content: {
    flex: 1,
  },
  applicationsList: {
    padding: scale(theme.spacing.md),
  },
  applicationCard: {
    backgroundColor: theme.colors.background.primary,
    borderRadius: theme.borderRadius.lg,
    padding: scale(theme.spacing.lg),
    marginBottom: verticalScale(theme.spacing.lg),
    ...getShadow('medium'),
    borderWidth: moderateScale(1),
    borderColor: 'transparent',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: verticalScale(theme.spacing.lg),
    paddingBottom: verticalScale(theme.spacing.sm),
    borderBottomWidth: moderateScale(1),
    borderBottomColor: theme.colors.border.light + '30',
  },
  cardHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    flex: 1,
  },
  categoryIndicator: {
    width: moderateScale(32),
    height: moderateScale(32),
    borderRadius: theme.borderRadius.full,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: scale(theme.spacing.sm),
  },
  cardHeaderInfo: {
    flex: 1,
    marginLeft: scale(theme.spacing.xs),
  },
  applicationId: {
    fontSize: moderateScale(theme.typography.bodySmall.fontSize),
    lineHeight: moderateScale(theme.typography.bodySmall.lineHeight),
    fontWeight: '700',
    color: theme.colors.text.primary,
    marginBottom: verticalScale(theme.spacing.xs),
  },
  applicationDate: {
    fontSize: moderateScale(12),
    lineHeight: moderateScale(theme.typography.caption.lineHeight),
    color: theme.colors.text.secondary,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: scale(theme.spacing.sm),
    paddingVertical: verticalScale(theme.spacing.xs),
    borderRadius: theme.borderRadius.full,
    alignSelf: 'flex-start',
  },
  statusText: {
    fontSize: moderateScale(theme.typography.caption.fontSize),
    lineHeight: moderateScale(theme.typography.caption.lineHeight),
    fontWeight: '600',
    marginLeft: scale(theme.spacing.xs),
  },
  lockIcon: {
    padding: scale(theme.spacing.xs),
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardContent: {
    marginBottom: verticalScale(theme.spacing.md),
  },
  jobCategory: {
    fontSize: moderateScale(theme.typography.h4.fontSize),
    fontWeight: '700',
    lineHeight: moderateScale(theme.typography.h4.lineHeight),
    color: theme.colors.text.primary,
    marginBottom: verticalScale(theme.spacing.sm),
  },
  position: {
    fontSize: moderateScale(theme.typography.body.fontSize),
    lineHeight: moderateScale(theme.typography.body.lineHeight),
    fontWeight: '600',
    color: theme.colors.text.primary,
    marginBottom: verticalScale(theme.spacing.xs),
  },
  organization: {
    fontSize: moderateScale(theme.typography.bodySmall.fontSize),
    lineHeight: moderateScale(theme.typography.bodySmall.lineHeight),
    color: theme.colors.text.secondary,
    marginBottom: verticalScale(theme.spacing.md),
  },
  applicationDetails: {
    backgroundColor: theme.colors.background.tertiary,
    borderRadius: theme.borderRadius.md,
    padding: scale(theme.spacing.sm),
    marginBottom: verticalScale(theme.spacing.md),
  },
  detailItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: verticalScale(theme.spacing.xs),
    borderBottomWidth: 0,
  },
  detailLabel: {
    fontSize: moderateScale(theme.typography.bodySmall.fontSize),
    lineHeight: moderateScale(theme.typography.bodySmall.lineHeight),
    color: theme.colors.text.secondary,
    flex: 1,
  },
  detailValue: {
    fontSize: moderateScale(theme.typography.bodySmall.fontSize),
    lineHeight: moderateScale(theme.typography.bodySmall.lineHeight),
    color: theme.colors.text.primary,
    fontWeight: '600',
    textAlign: 'right',
    maxWidth: '60%',
  },
  remarksContainer: {
    backgroundColor: theme.colors.status.warning + '10',
    borderRadius: theme.borderRadius.md,
    padding: scale(theme.spacing.sm),
    borderWidth: moderateScale(1),
    borderColor: theme.colors.status.warning + '30',
  },
  remarksLabel: {
    fontSize: moderateScale(theme.typography.bodySmall.fontSize),
    lineHeight: moderateScale(theme.typography.bodySmall.lineHeight),
    fontWeight: '600',
    color: theme.colors.status.warning,
    marginBottom: verticalScale(theme.spacing.xs),
  },
  remarksText: {
    fontSize: moderateScale(theme.typography.bodySmall.fontSize),
    lineHeight: moderateScale(theme.typography.bodySmall.lineHeight),
    color: theme.colors.text.primary,
  },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  progressIndicator: {
    flex: 1,
    marginRight: scale(theme.spacing.sm),
  },
  progressBar: {
    height: moderateScale(4),
    backgroundColor: theme.colors.border.light,
    borderRadius: theme.borderRadius.sm,
    marginBottom: verticalScale(theme.spacing.xs),
  },
  progressFill: {
    height: '100%',
    borderRadius: theme.borderRadius.sm,
  },
  progressText: {
    fontSize: moderateScale(theme.typography.caption.fontSize),
    lineHeight: moderateScale(theme.typography.caption.lineHeight),
    color: theme.colors.text.secondary,
  },
  viewButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: scale(theme.spacing.sm),
    paddingVertical: verticalScale(theme.spacing.xs),
    borderRadius: theme.borderRadius.md,
    backgroundColor: theme.colors.accent.medicalBlue + '20',
  },
  viewButtonText: {
    fontSize: moderateScale(theme.typography.bodySmall.fontSize),
    lineHeight: moderateScale(theme.typography.bodySmall.lineHeight),
    color: theme.colors.accent.medicalBlue,
    fontWeight: '600',
    marginRight: scale(theme.spacing.xs),
  },
  fab: {
    position: 'absolute',
    bottom: verticalScale(theme.spacing.xxxl),
    right: scale(theme.spacing.lg),
    width: moderateScale(56),
    height: moderateScale(56),
    borderRadius: theme.borderRadius.full,
    backgroundColor: theme.colors.accent.medicalBlue,
    justifyContent: 'center',
    alignItems: 'center',
    ...getShadow('large'),
    zIndex: 1,
  },
});
