import { StyleSheet } from 'react-native';
import { getBorderRadius, getColor, getShadow, getSpacing, getTypography } from '../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: getColor('background.secondary'),
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: getSpacing('lg'),
    paddingVertical: getSpacing('md'),
    backgroundColor: getColor('background.primary'),
    borderBottomWidth: 1,
    borderBottomColor: getColor('border.light'),
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: getBorderRadius('full'),
    backgroundColor: getColor('background.secondary'),
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    flex: 1,
    ...getTypography('h3'),
    color: getColor('text.primary'),
    textAlign: 'center',
    marginHorizontal: getSpacing('md'),
  },
  headerSpacer: {
    width: 40,
  },
  scrollView: {
    flex: 1,
  },
  instructionsContainer: {
    margin: getSpacing('lg'),
    padding: getSpacing('md'),
    backgroundColor: getColor('primary.light'),
    borderRadius: getBorderRadius('lg'),
    borderLeftWidth: 4,
    borderLeftColor: getColor('primary.main'),
  },
  instructionsTitle: {
...getTypography('body'),
    color: getColor('text.primary'),
    marginBottom: getSpacing('xs'),
  },
  instructionsText: {
    ...getTypography('body'),
    color: getColor('text.secondary'),
    lineHeight: 20,
  },
  categoryContainer: {
    paddingHorizontal: getSpacing('lg'),
    marginBottom: getSpacing('lg'),
  },
  sectionTitle: {
    ...getTypography('h3'),
    fontWeight: '700',
    color: getColor('text.primary'),
    marginBottom: getSpacing('md'),
  },
  categoryCard: {
    backgroundColor: getColor('background.primary'),
    borderRadius: getBorderRadius('lg'),
    padding: getSpacing('lg'),
    marginBottom: getSpacing('md'),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    ...getShadow('small'),
    borderLeftWidth: 5,
  },
  selectedCategoryCard: {
    borderColor: getColor('primary.main'),
    borderWidth: 2,
    backgroundColor: getColor('primary.light'),
    ...getShadow('medium'),
  },
  categoryInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  colorIndicator: {
    width: 28,
    height: 28,
    borderRadius: getBorderRadius('full'),
    marginRight: getSpacing('md'),
    ...getShadow('small'),
  },
  categoryDetails: {
    flex: 1,
  },
  categoryName: {
...getTypography('body'),
    fontWeight: '600',
    color: getColor('text.primary'),
    marginBottom: getSpacing('xs'),
  },
  cardType: {
    ...getTypography('body'),
    color: getColor('text.secondary'),
    marginBottom: getSpacing('xs'),
  },
  orientationBadge: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  orientationText: {
    ...getTypography('caption'),
    color: getColor('primary.main'),
    marginLeft: getSpacing('xs'),
  },
  requirementsContainer: {
    paddingHorizontal: getSpacing('lg'),
    marginBottom: getSpacing('lg'),
  },
  requirementsSummary: {
    backgroundColor: getColor('primary.light'),
    borderRadius: getBorderRadius('lg'),
    padding: getSpacing('lg'),
    marginBottom: getSpacing('md'),
    ...getShadow('small'),
    borderLeftWidth: 4,
    borderLeftColor: getColor('primary.main'),
  },
  summaryItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: getSpacing('xs'),
  },
  summaryText: {
    ...getTypography('body'),
    color: getColor('text.primary'),
    marginLeft: getSpacing('xs'),
  },
  documentsList: {
    marginBottom: getSpacing('lg'),
  },
  requirementItem: {
    backgroundColor: getColor('background.primary'),
    borderRadius: getBorderRadius('lg'),
    padding: getSpacing('lg'),
    marginBottom: getSpacing('md'),
    flexDirection: 'row',
    alignItems: 'flex-start',
    ...getShadow('small'),
    borderLeftWidth: 3,
    borderLeftColor: getColor('primary.main'),
  },
  requirementIcon: {
    width: 48,
    height: 48,
    borderRadius: getBorderRadius('full'),
    backgroundColor: getColor('primary.light'),
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: getSpacing('md'),
  },
  requirementDetails: {
    flex: 1,
  },
  requirementName: {
...getTypography('body'),
    fontWeight: '600',
    color: getColor('text.primary'),
    marginBottom: getSpacing('xs'),
  },
  requirementDescription: {
    ...getTypography('body'),
    color: getColor('text.secondary'),
    lineHeight: 18,
    marginBottom: getSpacing('xs'),
  },
  requiredBadge: {
    alignSelf: 'flex-start',
    backgroundColor: getColor('success.main'),
    paddingHorizontal: getSpacing('sm'),
    paddingVertical: getSpacing('xs'),
    borderRadius: getBorderRadius('full'),
  },
  requiredText: {
    ...getTypography('caption'),
    color: getColor('background.primary'),
    fontWeight: '700',
    fontSize: 11,
  },
  paymentContainer: {
    backgroundColor: getColor('background.primary'),
    borderRadius: getBorderRadius('lg'),
    padding: getSpacing('lg'),
    marginBottom: getSpacing('lg'),
    ...getShadow('small'),
    borderTopWidth: 4,
    borderTopColor: getColor('success.main'),
  },
  paymentTitle: {
    ...getTypography('body'),
    fontSize: 16,
    fontWeight: '700',
    color: getColor('text.primary'),
    marginBottom: getSpacing('md'),
  },
  paymentOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: getSpacing('sm'),
    borderBottomWidth: 1,
    borderBottomColor: getColor('background.secondary'),
  },
  paymentIcon: {
    width: 48,
    height: 48,
    borderRadius: getBorderRadius('md'),
    backgroundColor: getColor('background.secondary'),
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: getSpacing('md'),
  },
  paymentDetails: {
    flex: 1,
  },
  paymentMethod: {
    ...getTypography('body'),
    color: getColor('text.primary'),
    fontWeight: '600',
  },
  paymentDescription: {
    ...getTypography('caption'),
    color: getColor('text.secondary'),
  },
  paymentNote: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: getSpacing('sm'),
    padding: getSpacing('sm'),
    backgroundColor: getColor('warning.light'),
    borderRadius: getBorderRadius('sm'),
  },
  paymentNoteText: {
    ...getTypography('caption'),
    color: getColor('warning.dark'),
    marginLeft: getSpacing('xs'),
    flex: 1,
    lineHeight: 16,
  },
  actionButtons: {
    marginBottom: getSpacing('xl'),
  },
  primaryButton: {
    backgroundColor: getColor('primary.main'),
    borderRadius: getBorderRadius('lg'),
    paddingVertical: getSpacing('lg'),
    alignItems: 'center',
    marginBottom: getSpacing('sm'),
    ...getShadow('medium'),
  },
  primaryButtonText: {
...getTypography('button'),
    color: getColor('text.white'),
  },
  secondaryButton: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: getColor('primary.main'),
    borderRadius: getBorderRadius('lg'),
    paddingVertical: getSpacing('md'),
    alignItems: 'center',
  },
  secondaryButtonText: {
...getTypography('button'),
    color: getColor('primary.main'),
  },
  loadingState: {
    alignItems: 'center',
    paddingVertical: getSpacing('xxxl'),
    paddingHorizontal: getSpacing('xl'),
  },
  loadingTitle: {
    ...getTypography('h3'),
    color: getColor('primary.main'),
    marginTop: getSpacing('md'),
    marginBottom: getSpacing('xs'),
  },
  loadingDescription: {
    ...getTypography('body'),
    color: getColor('text.secondary'),
    textAlign: 'center',
    lineHeight: 20,
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: getSpacing('xxxl'),
    paddingHorizontal: getSpacing('xl'),
  },
  emptyIconContainer: {
    width: 120,
    height: 120,
    borderRadius: getBorderRadius('full'),
    backgroundColor: getColor('primary.light'),
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: getSpacing('lg'),
  },
  emptyTitle: {
    ...getTypography('h3'),
    color: getColor('text.secondary'),
    marginTop: getSpacing('md'),
    marginBottom: getSpacing('xs'),
  },
  emptyDescription: {
    ...getTypography('body'),
    color: getColor('text.secondary'),
    textAlign: 'center',
    lineHeight: 20,
  },
});
