import { StyleSheet } from 'react-native';
import { getBorderRadius, getColor, getShadow, getSpacing, getTypography } from '@shared/styles/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: getColor('background.secondary'),
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: getSpacing('lg'),
    paddingVertical: getSpacing('md'),
    backgroundColor: getColor('background.primary'),
  },
  backButton: {
    padding: getSpacing('xs'),
  },
  headerTitle: {
    ...getTypography('h3'),
    color: getColor('text.primary'),
    fontWeight: '600',
  },
  headerSpacer: {
    width: 40,
  },
  infoCard: {
    backgroundColor: getColor('background.primary'),
    margin: getSpacing('lg'),
    padding: getSpacing('xl'),
    borderRadius: getBorderRadius('lg'),
    alignItems: 'center',
    ...getShadow('small'),
  },
  iconContainer: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: getColor('primary.light') + '20',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: getSpacing('md'),
  },
  paymentMethodTitle: {
    ...getTypography('h3'),
    color: getColor('text.primary'),
    fontWeight: '600',
    marginBottom: getSpacing('xs'),
  },
  paymentMethodDescription: {
    ...getTypography('body'),
    color: getColor('text.secondary'),
    textAlign: 'center',
  },
  amountCard: {
    backgroundColor: getColor('background.primary'),
    marginHorizontal: getSpacing('lg'),
    marginBottom: getSpacing('lg'),
    padding: getSpacing('lg'),
    borderRadius: getBorderRadius('lg'),
    ...getShadow('small'),
  },
  sectionTitle: {
    ...getTypography('h4'),
    color: getColor('text.primary'),
    fontWeight: '600',
    marginBottom: getSpacing('md'),
  },
  feeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: getSpacing('xs'),
  },
  feeLabel: {
    ...getTypography('body'),
    color: getColor('text.secondary'),
  },
  feeValue: {
    ...getTypography('body'),
    color: getColor('text.primary'),
    fontWeight: '500',
  },
  totalRow: {
    borderTopWidth: 1,
    borderTopColor: getColor('border.light'),
    paddingTop: getSpacing('sm'),
    marginTop: getSpacing('xs'),
  },
  totalLabel: {
    ...getTypography('body'),
    color: getColor('text.primary'),
    fontWeight: '600',
  },
  totalValue: {
    ...getTypography('h4'),
    color: getColor('success.main'),
    fontWeight: '700',
  },
  instructionsCard: {
    backgroundColor: getColor('primary.light') + '15',
    marginHorizontal: getSpacing('lg'),
    marginBottom: getSpacing('lg'),
    padding: getSpacing('lg'),
    borderRadius: getBorderRadius('lg'),
    borderWidth: 1,
    borderColor: getColor('primary.light') + '40',
  },
  instructionsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: getSpacing('sm'),
  },
  instructionsTitle: {
    ...getTypography('body'),
    color: getColor('text.primary'),
    fontWeight: '600',
    marginLeft: getSpacing('xs'),
  },
  instructionStep: {
    ...getTypography('body'),
    color: getColor('text.secondary'),
    lineHeight: 22,
    marginBottom: getSpacing('xs'),
  },
  inputContainer: {
    marginHorizontal: getSpacing('lg'),
    marginBottom: getSpacing('lg'),
  },
  inputLabel: {
    ...getTypography('body'),
    color: getColor('text.primary'),
    fontWeight: '600',
    marginBottom: getSpacing('xs'),
  },
  textInput: {
    ...getTypography('body'),
    backgroundColor: getColor('background.primary'),
    borderWidth: 1,
    borderColor: getColor('border.light'),
    borderRadius: getBorderRadius('md'),
    padding: getSpacing('md'),
    color: getColor('text.primary'),
  },
  inputError: {
    borderColor: getColor('semantic.error'),
  },
  errorText: {
    ...getTypography('caption'),
    color: getColor('semantic.error'),
    marginTop: getSpacing('xs'),
  },
  uploadContainer: {
    marginHorizontal: getSpacing('lg'),
    marginBottom: getSpacing('lg'),
  },
  uploadButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: getColor('background.primary'),
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: getColor('primary.main'),
    borderRadius: getBorderRadius('lg'),
    padding: getSpacing('xl'),
    marginBottom: getSpacing('sm'),
  },
  uploadButtonError: {
    borderColor: getColor('semantic.error'),
  },
  uploadButtonText: {
    ...getTypography('body'),
    color: getColor('primary.main'),
    fontWeight: '600',
    marginLeft: getSpacing('sm'),
  },
  cameraButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: getColor('background.primary'),
    borderWidth: 1,
    borderColor: getColor('border.light'),
    borderRadius: getBorderRadius('lg'),
    padding: getSpacing('md'),
  },
  cameraButtonText: {
    ...getTypography('body'),
    color: getColor('primary.main'),
    fontWeight: '500',
    marginLeft: getSpacing('sm'),
  },
  previewContainer: {
    backgroundColor: getColor('background.primary'),
    borderRadius: getBorderRadius('lg'),
    padding: getSpacing('md'),
    borderWidth: 1,
    borderColor: getColor('border.light'),
  },
  receiptPreview: {
    width: '100%',
    height: 200,
    borderRadius: getBorderRadius('md'),
    marginBottom: getSpacing('sm'),
    resizeMode: 'cover',
  },
  receiptInfo: {
    marginBottom: getSpacing('sm'),
  },
  receiptFileName: {
    ...getTypography('body'),
    color: getColor('text.primary'),
    fontWeight: '500',
    marginBottom: getSpacing('xs'),
  },
  receiptFileSize: {
    ...getTypography('caption'),
    color: getColor('text.secondary'),
  },
  removeButton: {
    alignSelf: 'flex-end',
  },
  progressContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: getSpacing('lg'),
    marginBottom: getSpacing('lg'),
    padding: getSpacing('md'),
    backgroundColor: getColor('primary.light') + '20',
    borderRadius: getBorderRadius('md'),
  },
  progressText: {
    ...getTypography('body'),
    color: getColor('primary.main'),
    marginLeft: getSpacing('sm'),
    fontWeight: '500',
  },
  submitContainer: {
    paddingHorizontal: getSpacing('lg'),
    paddingBottom: getSpacing('xxxl'),
  },
  submitButton: {
    width: '100%',
  },
});
